# Generated by Django 5.2.6 on 2025-10-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('street_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street_name', models.TextField(blank=True, null=True)),
                ('apt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True)),
                ('date_of_birth', models.TextField(blank=True, null=True)),
                ('date_of_registration', models.TextField(blank=True, null=True)),
                ('party', models.CharField(blank=True, max_length=2, null=True)),
                ('precinct', models.CharField(blank=True, max_length=10, null=True)),
                ('v20state', models.IntegerField(default=0)),
                ('v21town', models.IntegerField(default=0)),
                ('v21primary', models.IntegerField(default=0)),
                ('v22general', models.IntegerField(default=0)),
                ('v23town', models.IntegerField(default=0)),
                ('voter_score', models.IntegerField(default=0)),
            ],
        ),
    ]
