# Generated by Django 5.2.6 on 2025-12-08 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dininglocation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='joinrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mealpost',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(choices=[('Sports/Gym', 'Sports/Gym'), ('Gaming/Tech', 'Gaming/Tech'), ('Arts/Music', 'Arts/Music'), ('Outdoors', 'Outdoors'), ('Pop Culture', 'Pop Culture')], default='Pop Culture', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_battery',
            field=models.CharField(choices=[('Quiet Eater', 'Quiet Eater'), ('Casual Chat', 'Casual Chat'), ('Deep Conversations', 'Deep Conversations'), ('Non-stop Yapping', 'Non-stop Yapping')], default='Casual Chat', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spice_tolerance',
            field=models.CharField(choices=[('None', 'None'), ('Mild', 'Mild'), ('Medium', 'Medium'), ('Spicy', 'Spicy'), ('Ghost Pepper', 'Ghost Pepper')], default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.mealpost'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userprofile'),
        ),
        migrations.AlterField(
            model_name='mealpost',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userprofile'),
        ),
        migrations.AlterField(
            model_name='mealpost',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.dininglocation'),
        ),
        migrations.AlterField(
            model_name='mealpost',
            name='max_guests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.dininglocation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
