# Generated by Django 5.2.6 on 2025-12-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_dininglocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(choices=[('None', 'I eat everything 😋'), ('Vegan', 'Vegan 🌱'), ('Halal', 'Halal 🥩'), ('Other', 'Other 🍽️')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(choices=[('Sports/Gym', 'Sports/Gym 🏀'), ('Gaming/Tech', 'Gaming/Tech 🎮'), ('Arts/Music', 'Arts/Music 🎨'), ('Outdoors', 'Outdoors 🌲'), ('Pop Culture', 'Pop Culture 🎬')], default='Pop Culture', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_battery',
            field=models.CharField(choices=[('Quiet Eater', 'Quiet Eater 🤫'), ('Casual Chat', 'Casual Chat 💬'), ('Deep Conversations', 'Deep Conversations 🧠'), ('Non-stop Yapping', 'Non-stop Yapping 🗣️')], default='Casual Chat', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='spice_tolerance',
            field=models.CharField(choices=[('None', 'None 🥛'), ('Mild', 'Mild 🌶️'), ('Medium', 'Medium 🌶️🌶️'), ('Spicy', 'Spicy 🔥'), ('Ghost Pepper', 'Ghost Pepper 😵🌶️')], default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='usual_meal_time',
            field=models.CharField(choices=[('Breakfast', 'Brekkie 🥞'), ('Lunch', 'Lunch 🥪'), ('Dinner', 'Dinner 🍝'), ('Late Night', 'Late Night 🌙🍕')], default='Lunch', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vibe',
            field=models.CharField(choices=[('Quick meal', 'Quick meal ⚡'), ('Study + eat', 'Study + eat 📚'), ('Gym bros', 'Gym Bros 💪'), ('Social', 'Social 🎉'), ('Casual', 'Chill vibes 😎')], default='Casual', max_length=50),
        ),
    ]
