# Generated by Django 5.2.6 on 2025-12-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_userprofile_dietary_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealpost',
            name='end_time',
        ),
        migrations.AddField(
            model_name='mealpost',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
    ]
