# Generated by Django 5.2.6 on 2025-12-09 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_mealpost_end_time_mealpost_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealpost',
            name='duration',
        ),
    ]
