# Generated by Django 5.2.6 on 2025-12-09 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dininglocation',
            name='campus_area',
        ),
        migrations.RemoveField(
            model_name='dininglocation',
            name='is_on_campus',
        ),
        migrations.AddField(
            model_name='dininglocation',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='dininglocation',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dininglocation',
            name='location_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dininglocation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mealpost',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meals', to='project.userprofile'),
        ),
        migrations.AlterField(
            model_name='mealpost',
            name='max_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mealpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(choices=[('None', 'I eat everything 😋'), ('Vegetarian', 'Vegetarian 🥗'), ('Vegan', 'Vegan 🌱'), ('Halal', 'Halal 🥩'), ('Kosher', 'Kosher 🕍'), ('Gluten-Free', 'Gluten-Free 🌾'), ('Nut-Free', 'Nut-Free 🥜')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(choices=[('Sports', 'Sports 🏀'), ('Tech', 'Tech & Coding 💻'), ('Arts', 'Arts & Music 🎨'), ('Gaming', 'Gaming 🎮'), ('Outdoors', 'Outdoors 🌲'), ('Movies', 'Movies & TV 🎬')], default='Tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_battery',
            field=models.CharField(choices=[('Low', 'Low 🪫'), ('Medium', 'Medium 🔋'), ('High', 'High ⚡'), ('Casual', 'Casual Chat 💬')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='spice_tolerance',
            field=models.CharField(choices=[('None', 'None 🥛'), ('Mild', 'Mild 🌶️'), ('Medium', 'Medium 🌶️🌶️'), ('Hot', 'Hot 🌶️🌶️🌶️'), ('Extreme', 'Extreme 🔥')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='usual_meal_time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast (7am-10am) 🍳'), ('Lunch', 'Lunch (11am-2pm) 🥪'), ('Dinner', 'Dinner (5pm-8pm) 🍝'), ('Late Night', 'Late Night (9pm-12am) 🌙')], default='Lunch', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vibe',
            field=models.CharField(choices=[('Chatty', 'Chatty & Social 🗣️'), ('Quiet', 'Quiet & Chill 🤫'), ('Quick', 'Quick Eat 🏃'), ('Study', 'Study & Eat 📚')], default='Chatty', max_length=20),
        ),
        migrations.CreateModel(
            name='MealMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='project.mealpost')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userprofile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
